name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image for Linux (amd64)
        if: github.event_name == 'push'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fast-music-remover:latest .

      - name: Push Docker Image for Linux (amd64)
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fast-music-remover:latest

      - name: Enable Buildx for Multi-Platform
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for macOS Test (amd64 workaround)
        if: github.event_name == 'pull_request'
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64 \
            --tag ghcr.io/${{ github.repository_owner }}/fast-music-remover:macos-test \
            --load .

      - name: Push Docker Image for macOS Test (amd64 workaround)
        if: github.event_name == 'pull_request'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fast-music-remover:macos-test
